// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/catchup_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i3;

import 'package:bible_feed/manager/app_lifecycle_manager.dart' as _i2;
import 'package:bible_feed/manager/feed_manager.dart' as _i9;
import 'package:bible_feed/manager/feeds_advance_manager.dart' as _i10;
import 'package:bible_feed/manager/feeds_manager.dart' as _i8;
import 'package:bible_feed/manager/midnight_manager.dart' as _i12;
import 'package:bible_feed/model/catchup_setting.dart' as _i5;
import 'package:bible_feed/model/feeds_advance_state.dart' as _i11;
import 'package:bible_feed/model/priority.dart' as _i4;
import 'package:bible_feed/service/date_time_service.dart' as _i7;
import 'package:bible_feed/service/store_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLifecycleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLifecycleManager extends _i1.Mock
    implements _i2.AppLifecycleManager {
  @override
  void onResume(
    _i3.VoidCallback? callback, {
    _i4.Priority? priority = _i4.Priority.normal,
  }) => super.noSuchMethod(
    Invocation.method(#onResume, [callback], {#priority: priority}),
    returnValueForMissingStub: null,
  );

  @override
  void runCallbacks() => super.noSuchMethod(
    Invocation.method(#runCallbacks, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CatchupSetting].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatchupSetting extends _i1.Mock implements _i5.CatchupSetting {
  @override
  bool get defaultValue =>
      (super.noSuchMethod(
            Invocation.getter(#defaultValue),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get storeKeyFragment =>
      (super.noSuchMethod(
            Invocation.getter(#storeKeyFragment),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storeKeyFragment),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storeKeyFragment),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get subtitle =>
      (super.noSuchMethod(
            Invocation.getter(#subtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
          )
          as String);

  @override
  bool get isAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get storeKey =>
      (super.noSuchMethod(
            Invocation.getter(#storeKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storeKey),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#storeKey),
            ),
          )
          as String);

  @override
  bool get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set value(bool? value) => super.noSuchMethod(
    Invocation.setter(#value, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i7.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}

/// A class which mocks [FeedsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsManager extends _i1.Mock implements _i8.FeedsManager {
  @override
  bool get areChaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#areChaptersRead),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get chaptersToRead =>
      (super.noSuchMethod(
            Invocation.getter(#chaptersToRead),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i9.FeedManager> get feeds =>
      (super.noSuchMethod(
            Invocation.getter(#feeds),
            returnValue: <_i9.FeedManager>[],
            returnValueForMissingStub: <_i9.FeedManager>[],
          )
          as List<_i9.FeedManager>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedsAdvanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsAdvanceManager extends _i1.Mock
    implements _i10.FeedsAdvanceManager {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i11.FeedsAdvanceState advance() =>
      (super.noSuchMethod(
            Invocation.method(#advance, []),
            returnValue: _i11.FeedsAdvanceState.notAllRead,
            returnValueForMissingStub: _i11.FeedsAdvanceState.notAllRead,
          )
          as _i11.FeedsAdvanceState);

  @override
  _i11.FeedsAdvanceState maybeAdvance() =>
      (super.noSuchMethod(
            Invocation.method(#maybeAdvance, []),
            returnValue: _i11.FeedsAdvanceState.notAllRead,
            returnValueForMissingStub: _i11.FeedsAdvanceState.notAllRead,
          )
          as _i11.FeedsAdvanceState);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MidnightManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMidnightManager extends _i1.Mock implements _i12.MidnightManager {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(
    _i3.VoidCallback? listener, {
    _i4.Priority? priority = _i4.Priority.normal,
  }) => super.noSuchMethod(
    Invocation.method(#addListener, [listener], {#priority: priority}),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreService extends _i1.Mock implements _i13.StoreService {
  @override
  T? get<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  _i14.Future<void> set<T>(String? key, T? value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}
