// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/feeds_advance_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i7;

import 'package:bible_feed/manager/feed_advance_manager.dart' as _i8;
import 'package:bible_feed/manager/feed_manager.dart' as _i3;
import 'package:bible_feed/manager/feeds_manager.dart' as _i9;
import 'package:bible_feed/model/book.dart' as _i2;
import 'package:bible_feed/model/reading_list.dart' as _i5;
import 'package:bible_feed/service/date_time_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBook_1 extends _i1.SmartFake implements _i2.Book {
  _FakeBook_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFeed_2 extends _i1.SmartFake implements _i3.Feed {
  _FakeFeed_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i4.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}

/// A class which mocks [FeedManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedManager extends _i1.Mock implements _i3.FeedManager {
  @override
  _i2.Book get book =>
      (super.noSuchMethod(
            Invocation.getter(#book),
            returnValue: _FakeBook_1(this, Invocation.getter(#book)),
            returnValueForMissingStub: _FakeBook_1(
              this,
              Invocation.getter(#book),
            ),
          )
          as _i2.Book);

  @override
  int get bookIndex =>
      (super.noSuchMethod(
            Invocation.getter(#bookIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get chaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#chaptersRead),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double get progress =>
      (super.noSuchMethod(
            Invocation.getter(#progress),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i5.ReadingList get readingList =>
      (super.noSuchMethod(
            Invocation.getter(#readingList),
            returnValue: _i6.dummyValue<_i5.ReadingList>(
              this,
              Invocation.getter(#readingList),
            ),
            returnValueForMissingStub: _i6.dummyValue<_i5.ReadingList>(
              this,
              Invocation.getter(#readingList),
            ),
          )
          as _i5.ReadingList);

  @override
  _i3.Feed get feed =>
      (super.noSuchMethod(
            Invocation.getter(#feed),
            returnValue: _FakeFeed_2(this, Invocation.getter(#feed)),
            returnValueForMissingStub: _FakeFeed_2(
              this,
              Invocation.getter(#feed),
            ),
          )
          as _i3.Feed);

  @override
  set feed(_i3.Feed? value) => super.noSuchMethod(
    Invocation.setter(#feed, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setBookChapterVerse(int? bookIndex, int? chapter, [int? verse = 1]) =>
      super.noSuchMethod(
        Invocation.method(#setBookChapterVerse, [bookIndex, chapter, verse]),
        returnValueForMissingStub: null,
      );

  @override
  void toggleIsRead() => super.noSuchMethod(
    Invocation.method(#toggleIsRead, []),
    returnValueForMissingStub: null,
  );

  @override
  void touch() => super.noSuchMethod(
    Invocation.method(#touch, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedAdvanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedAdvanceManager extends _i1.Mock
    implements _i8.FeedAdvanceManager {
  @override
  void advance(_i3.FeedManager? feedManager) => super.noSuchMethod(
    Invocation.method(#advance, [feedManager]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsManager extends _i1.Mock implements _i9.FeedsManager {
  @override
  bool get areChaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#areChaptersRead),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get chaptersToRead =>
      (super.noSuchMethod(
            Invocation.getter(#chaptersToRead),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i3.FeedManager> get feedManagers =>
      (super.noSuchMethod(
            Invocation.getter(#feedManagers),
            returnValue: <_i3.FeedManager>[],
            returnValueForMissingStub: <_i3.FeedManager>[],
          )
          as List<_i3.FeedManager>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
